<?php
namespace PvPGNTracker\Templates;
$nav = true;
$solicitation = $this->getContext()->solicitation;

if (!$solicitation) {
  $title = 'Server Not Found';
  require('./Includes/header.inc.phtml');
  require('./Includes/NotFound.inc.phtml');
} else {
  $title = 'Server View';
  $view_server_url = \PvPGNTracker\Libraries\UrlFormatter::format(sprintf('/server/%s:%d', $solicitation->server_address, $solicitation->server_port));
  require('./Includes/header.inc.phtml');
?>
<h1><?=$title?></h1>
<p class="lead">This server has been checking in recently.</p>

<table id="servers" class="table table-hover table-sm">
  <thead>
    <tr>
      <th scope="col" style="min-width:64px;"></th>
      <th scope="col">Address</th>
      <th scope="col">Location</th>
      <th scope="col">Description</th>
      <th scope="col">Contact</th>
      <th scope="col">Uptime</th>
      <th scope="col">Software</th>
      <th scope="col">Users</th>
      <th scope="col">Games</th>
      <th scope="col">Channels</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><a href="<?=$view_server_url?>.json" title="View Server as Json">⚙️</a> <a href="<?=$view_server_url?>.txt" title="View Server as Plaintext">🗒️</a> <a href="<?=$view_server_url?>" title="View Server as Webpage">🔎</a></td>
      <td><address><?=$solicitation->server_address?>:<?=$solicitation->server_port?></address></td>
      <td><img style="height:1.25em;" src="<?=$solicitation->country_flag[0]?>" alt="<?=$solicitation->country_flag[1]?>" title="<?=$solicitation->country_flag[2]?>"/> <?=$solicitation->server_location?></td>
      <td><?=$solicitation->server_description?></td>
<?php if (!empty($solicitation->contact_email)) { ?>
      <td><a href="mailto:<?=$solicitation->contact_email?>"><?=$solicitation->contact_name?></a><br/><a href="<?=$solicitation->server_url[0]?>"><?=$solicitation->server_url[1]?></a></td>
<?php } else { ?>
      <td><?=$solicitation->contact_name?><br/><a href="<?=$solicitation->server_url[0]?>"><?=$solicitation->server_url[1]?></a></td>
<?php } ?>
      <td><?=$solicitation->uptime?></td>
      <td><?=$solicitation->software?> (<?=$solicitation->version?>) on <?=$solicitation->platform?></td>
      <td><?=$solicitation->active_users?>&nbsp;active, <?=$solicitation->total_logins?>&nbsp;logins</td>
      <td><?=$solicitation->active_games?>&nbsp;active, <?=$solicitation->total_games?>&nbsp;total</td>
      <td><?=$solicitation->active_channels?>&nbsp;active</td>
    </tr>
  </tbody>
</table>

<script type="text/javascript">
  $(document).ready(function(){
    $('#servers').DataTable();
  });
</script>

<?php } ?>
<?php require( './Includes/footer.inc.phtml' ); ?>
