<?php namespace PvPGNTracker\Templates;
use \PvPGNTracker\Libraries\VersionInfo; ?>
    </main>
    <footer class="footer bg-dark">
      <div class="container">
        <p class="text-muted mb-0">
          Developed with <img alt="love" title="love" src="/images/heart.png" style="height:16px;"/> at
<?php if ( VersionInfo::$version['pvpgntracker'] ) { ?>
          <a href="https://github.com/BNETDocs/pvpgn-tracker/tree/<?=VersionInfo::$version['pvpgntracker'][1]?>" rel="external" title="Contribute to the source code!">pvpgn-tracker-web</a> (<?=VersionInfo::$version['pvpgntracker'][0]?>)
<?php } else { ?>
          <a href="https://github.com/BNETDocs/pvpgn-tracker">pvpgn-tracker</a> (Development)
<?php } ?>
        </p>
      </div>
    </footer>

    <script type="text/javascript" src="/js/jquery-3.7.0.slim.min.js" integrity="sha384-w5y/xIeYixWvfM+A1cEbmHPURnvyqmVg5eVENruEdDjcyRLUSNej7512JQGspFUr"><![CDATA[]]></script>
    <script type="text/javascript" src="/js/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"><![CDATA[]]></script>
    <script type="text/javascript" src="/js/jquery.dataTables.min.js" charset="utf8"><![CDATA[]]></script>
    <script type="text/javascript" src="/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"><![CDATA[]]></script>

  </body>
</html>
