<!DOCTYPE html>
<html lang="en">
  <head>

    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>

    <title>Internal Error &ndash; pvpgn-tracker</title>

    <link rel="stylesheet" type="text/css" media="all" href="/css/bootstrap.min.css"/>
    <link rel="stylesheet" type="text/css" media="all" href="/css/jquery.dataTables.min.css"/>
    <link rel="stylesheet" type="text/css" media="all" href="/css/main.css"/>

    <meta name="keywords" content="pvpgn,tracker,track,telemetry,diablo,starcraft,warcraft"/>

    <meta property="og:site_name" content="pvpgn-tracker"/>
    <meta property="og:locale" content="en_US"/>
    <meta property="twitter:card" content="summary"/>
    <meta property="og:title" content="Not Found"/>
    <meta property="twitter:title" content="Not Found"/>

  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="/">pvpgn-tracker</a>
      </nav>
    </header>
    <main class="container">

      <div class="alert alert-danger" role="alert" style="margin-top:15px;">
        <h4 class="alert-heading">Internal Error</h4>
        <p>An internal error occurred. Please <a href="https://github.com/BNETDocs/pvpgn-tracker-web/issues/new?title=Internal%20Error">submit an issue</a> so it can be investigated.</p>
        <hr/>
        <p>What to include in your report:
          <ul>
            <li>Steps to reproduce the issue.</li>
            <li>How you encountered the issue.</li>
            <li>What your intention was and what you expected to happen.</li>
            <li>If you feel it necessary, or if asked for, details about your environment.</li>
            <li>Your operating system and its version number (e.g. Windows 7 Pro 64-bit).</li>
            <li>Your browser and its version number (e.g. Chrome 50).</li>
          </ul>
        </p>
      </div>

    </main>
    <footer class="footer bg-dark">
      <div class="container">
        <p class="text-muted mb-0">
          Developed with <img alt="love" title="love" src="/heart.png" style="height:16px;"/> at
          <a href="https://github.com/BNETDocs/pvpgn-tracker-web">pvpgn-tracker-web</a> (Development)
        </p>
      </div>
    </footer>

    <script type="text/javascript" src="/js/jquery-3.7.0.slim.min.js" integrity="sha384-w5y/xIeYixWvfM+A1cEbmHPURnvyqmVg5eVENruEdDjcyRLUSNej7512JQGspFUr"><![CDATA[]]></script>
    <script type="text/javascript" src="/js/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"><![CDATA[]]></script>
    <script type="text/javascript" src="/js/jquery.dataTables.min.js" charset="utf8"><![CDATA[]]></script>
    <script type="text/javascript" src="/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"><![CDATA[]]></script>

  </body>
</html>
