<?php
namespace PvPGNTracker\Templates;
$title = 'Servers';
$nav = true;
require('./Includes/header.inc.phtml');
?>

<h1><?=$title?></h1>
<p class="lead">These are the active servers that have been reporting in.</p>

<table id="servers" class="table table-hover table-sm">
  <thead>
    <tr>
      <th scope="col" style="min-width:64px;"></th>
      <th scope="col">Address</th>
      <th scope="col">Location</th>
      <th scope="col">Description</th>
      <th scope="col">Contact</th>
      <th scope="col">Uptime</th>
      <th scope="col">Software</th>
      <th scope="col">Users</th>
      <th scope="col">Games</th>
      <th scope="col">Channels</th>
    </tr>
  </thead>
  <tbody>
<?php $rows = 0; foreach ($this->getContext()->servers as $server) { ++$rows;
    $solicitation = new \PvPGNTracker\Libraries\Solicitation($server);
    $view_server_url = \PvPGNTracker\Libraries\UrlFormatter::format(sprintf('/server/%s:%d', $server['ip_address'], $server['port'])); ?>
    <tr>
      <td><a href="<?=$view_server_url?>.json" title="View Server as Json">⚙️</a> <a href="<?=$view_server_url?>.txt" title="View Server as Plaintext">🗒️</a> <a href="<?=$view_server_url?>" title="View Server as Webpage">🔎</a></td>
      <td><address><?=$solicitation->server_address?>:<?=$solicitation->server_port?></address></td>
      <td><img style="height:1.25em;" src="<?=$solicitation->country_flag[0]?>" alt="<?=$solicitation->country_flag[1]?>" title="<?=$solicitation->country_flag[2]?>"/> <?=$solicitation->server_location?></td>
      <td><?=$solicitation->server_description?></td>
<?php if (!empty($solicitation->contact_email)) { ?>
      <td><a href="mailto:<?=$solicitation->contact_email?>"><?=$solicitation->contact_name?></a><br/><a href="<?=$solicitation->server_url[0]?>"><?=$solicitation->server_url[1]?></a></td>
<?php } else { ?>
      <td><?=$solicitation->contact_name?><br/><a href="<?=$solicitation->server_url[0]?>"><?=$solicitation->server_url[1]?></a></td>
<?php } ?>
      <td><?=$solicitation->uptime?></td>
      <td><?=$solicitation->software?> (<?=$solicitation->version?>) on <?=$solicitation->platform?></td>
      <td><?=$solicitation->active_users?>&nbsp;active, <?=$solicitation->total_logins?>&nbsp;logins</td>
      <td><?=$solicitation->active_games?>&nbsp;active, <?=$solicitation->total_games?>&nbsp;total</td>
      <td><?=$solicitation->active_channels?>&nbsp;active</td>
    </tr>
<?php } ?>
<?php if ( !$rows ) { ?>
    <tr>
      <td scope="row" colspan="10"><em>(no servers reporting.)</em></td>
    </tr>
<?php } else { ?>
    <tr><td colspan="10">Count: <?=$rows?></td></tr>
<?php } ?>
  </tbody>
</table>

<script type="text/javascript">
  $(document).ready(function(){
    $('#servers').DataTable();
  });
</script>

<?php require( './Includes/footer.inc.phtml' ); ?>
