<?php namespace PvPGNTracker\Templates; ?>
<?php $title = 'Servers'; $nav = true; require( './header.inc.phtml' ); ?>

<h1><?=$title?></h1>
<p class="lead">These are the active servers that have been reporting in.</p>

<table id="servers" class="table table-hover table-sm">
  <thead>
    <tr>
      <th scope="col">Address</th>
      <th scope="col">Location</th>
      <th scope="col">Description</th>
      <th scope="col">Contact</th>
      <th scope="col">Uptime</th>
      <th scope="col">Software</th>
      <th scope="col">Users</th>
      <th scope="col">Games</th>
      <th scope="col">Channels</th>
    </tr>
  </thead>
  <tbody>
<?php $rows = 0; foreach ( $this->getContext()->servers as $server ) { ++$rows; ?>
    <tr>
      <td><address><?=$server[ 'ip_address' ]?>:<?=$server[ 'port' ]?></address></td>
      <td><img style="height:1.25em;" src="<?=$server[ 'country_flag' ][ 0 ]?>" alt="<?=$server[ 'country_flag' ][ 1 ]?>" title="<?=$server[ 'country_flag' ][ 2 ]?>"/> <?=$server[ 'location' ]?></td>
      <td><?=$server[ 'description' ]?></td>
<?php if ( !empty( $server[ 'contact_email' ])) { ?>
      <td><a href="mailto:<?=$server[ 'contact_email' ]?>"><?=$server[ 'contact_name' ]?></a><br/><a href="<?=$server[ 'url' ][ 0 ]?>"><?=$server[ 'url' ][ 1 ]?></a></td>
<?php } else { ?>
      <td><?=$server[ 'contact_name' ]?><br/><a href="<?=$server[ 'url' ][ 0 ]?>"><?=$server[ 'url' ][ 1 ]?></a></td>
<?php } ?>
      <td><?=$server[ 'uptime' ]?></td>
      <td><?=$server[ 'software' ]?> (<?=$server[ 'version' ]?>) on <?=$server[ 'platform' ]?></td>
      <td><?=$server[ 'active_users' ]?>&nbsp;active, <?=$server[ 'total_logins' ]?>&nbsp;logins</td>
      <td><?=$server[ 'active_games' ]?>&nbsp;active, <?=$server[ 'total_games' ]?>&nbsp;total</td>
      <td><?=$server[ 'active_channels' ]?>&nbsp;active</td>
    </tr>
<?php } ?>
<?php if ( !$rows ) { ?>
    <tr>
      <td scope="row" colspan="8"><em>(no servers reporting.)</em></td>
    </tr>
<?php } else { ?>
    <tr><td colspan="9">Count: <?=$rows?></td></tr>
<?php } ?>
  </tbody>
</table>

<script type="text/javascript">
  $(document).ready(function(){
    $('#servers').DataTable();
  });
</script>

<?php require( './footer.inc.phtml' ); ?>
